In [5]:
import joblib
import pandas as pd
import numpy as np

In [14]:
model = joblib.load('artifacts\\model.joblib')

In [15]:
print(model)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['type_prepayment']),
                                                 ('num', 'passthrough',
                                                  ['item_price',
                                                   'delivery_days',
                                                   'client_is_app',
                                                   'historical_return_rate',
                                                   'avg_item_losses_30d'])])),
                ('regressor',
                 RandomForestRegressor(max_depth=8, n_estimators=40, n_jobs=1,
                                       random_state=42))])

In [41]:
print(model.steps[0][1].transformers)
req_features = set()
for i in model.steps[0][1].transformers:
    req_features.update(i[2])
req_features

{'avg_item_losses_30d',
 'client_is_app',
 'delivery_days',
 'historical_return_rate',
 'item_price',
 'type_prepayment'}

In [6]:
data = pd.read_csv('artifacts\\item_features.csv', index_col = 'item_id')
data['updated_at'] = pd.to_datetime(data['updated_at'], utc=True)

In [7]:
data

,historical_return_rate,avg_item_losses_30d,updated_at
item_id,,,
ITEM-001,0.773956,623.1971,2026-03-21 02:00:00+00:00
ITEM-002,0.438878,107.6418,2026-02-12 23:00:00+00:00
ITEM-003,0.858598,428.8544,2026-03-30 15:00:00+00:00
ITEM-004,0.697368,411.3783,2026-03-10 12:00:00+00:00
ITEM-005,0.094177,686.0577,2026-02-28 13:00:00+00:00
...,...,...,...
ITEM-296,0.902653,222.4177,2026-02-08 19:00:00+00:00
ITEM-297,0.979571,562.4268,2026-02-19 14:00:00+00:00
ITEM-298,0.802026,507.0158,2026-03-12 06:00:00+00:00
ITEM-299,0.779478,785.4448,2026-02-12 01:00:00+00:00
ITEM-300,0.642483,496.2862,2026-03-17 17:00:00+00:00

In [8]:
data.describe()

       historical_return_rate  avg_item_losses_30d
count              300.000000           300.000000
mean                 0.486653           404.255693
std                  0.290306           227.433406
min                  0.007362             4.343900
25%                  0.227156           216.562250
50%                  0.479004           410.784850
75%                  0.750978           598.178900
max                  0.992376           799.283800

In [2]:
import json
with open('artifacts\\model_metadata.json', 'r') as json_file:
    jsn = json.load(json_file)
print(jsn)

{'model_name': 'item-loss-predictor', 'model_version': '1.0.0', 'target': 'item_losses', 'features': ['item_price', 'delivery_days', 'client_is_app', 'type_prepayment', 'historical_return_rate', 'avg_item_losses_30d'], 'feature_types': {'item_price': 'float', 'delivery_days': 'integer', 'client_is_app': 'boolean', 'type_prepayment': 'string', 'historical_return_rate': 'float', 'avg_item_losses_30d': 'float'}, 'sklearn_version': '1.6.1', 'created_at': '2026-01-01T00:00:00Z'}

In [47]:
print(set(jsn))
print(list(model.feature_names_in_) == jsn["features"])

{'model_name', 'feature_types', 'model_version', 'sklearn_version', 'target', 'features', 'created_at'}
True

In [50]:
model_version = jsn["model_version"]
model_version

'1.0.0'

In [10]:
dtype_map = {
    "float": "float64",
    "integer": "int64",
    "boolean": "bool",
    "string": "object",
}
dtypes = {k: dtype_map[v] for k, v in jsn['feature_types'].items()}

In [62]:
request = {
  "request_id": "9e597dee-4253-4a30-8ec3-20a1cb10d56f",
  "item_id": "ITEM-001",
  "item_price": 2500.0,
  "delivery_days": 4,
  "client_is_app": True,
  "type_prepayment": "card"
}

item = data.loc[request['item_id']]
if isinstance(item, pd.DataFrame):
    item = item.sort_values('updated_at').iloc[-1]

process_req = request.copy()
process_req |= dict(item)



X = pd.DataFrame([{
    i: process_req[i] for i in jsn['features']
}])


predict = model.predict(X)[0]

response = {
    'request_id': process_req['request_id'],
    'prediction': float(predict),
    'model_version': jsn['model_version']
}

print(response)

{'request_id': '9e597dee-4253-4a30-8ec3-20a1cb10d56f', 'prediction': 501.3364060204059, 'model_version': '1.0.0'}

In [19]:
from sqlalchemy import create_engine, inspect
from app.models import Base
e = create_engine('postgresql+psycopg://app:app@localhost:5432/app_test')
Base.metadata.drop_all(e)
Base.metadata.create_all(e)
inspector = inspect(e)

a = inspector.get_columns("item_features")
print([i['name'] for i in a])
b = inspector.get_columns("predictions")
print([i['name'] for i in b])

['item_id', 'historical_return_rate', 'avg_item_losses_30d', 'updated_at']
['request_id', 'item_id', 'model_version', 'item_price', 'delivery_days', 'client_is_app', 'type_prepayment', 'historical_return_rate', 'avg_item_losses_30d', 'created_at', 'prediction']